---
- name: Install dependencies
  ansible.builtin.package:
    name: git
    state: present
  become: true

- name: Clone dotfile repo to $HOME/.dots
  ansible.builtin.git:
    repo: "{{ dots_repo }}"
    dest: "/home/{{ user | default(ansible_user) }}/.dots"
    bare: true
  become: false

- name: Check out dotfile repo to $HOME
  ansible.builtin.command: # built-in module can't replicate this behavior
    cmd: "/usr/bin/git --git-dir=/home/{{ user | default(ansible_user) }}/.dots/ --work-tree=/home/{{ user | default(ansible_user) }}/ checkout" # noqa: command-instead-of-module
    creates: "/home/{{ user | default(ansible_user) }}/.zshenv"
  failed_when: false
  become: false

- name: Turn off status.showUntrackedFiles
  community.general.git_config:
    name: status.showUntrackedFiles
    value: "no"
    scope: local
    repo: "/home/{{ user | default(ansible_user) }}/.dots"
  become: false

- name: Set origin url to ssh
  community.general.git_config:
    name: remote.origin.url
    value: "{{ dots_repo | regex_replace('^https://([^/]+)/(.+)$', 'git@\\1:\\2') }}"
    scope: local
    repo: "/home/{{ user | default(ansible_user) }}/.dots"
  become: false
