---
- name: Configure Arch Linux
  hosts: localhost
  vars_files: vars.yml
  become: true
  roles:
    - { role: pacman, tags: pacman }
    - { role: btrfs, tags: btrfs }
    - { role: systemd, tags: systemd }
    - { role: udev, tags: udev }
    - { role: zram, tags: zram }
    - { role: ananicy, tags: ananicy }
    - { role: firewalld, tags: firewalld }
    - { role: dots, tags: dots }
    - { role: zsh, tags: zsh }
