---
- name: Configure GA402R laptop
  hosts: localhost
  vars_files: vars.yml
  become: true
  roles:
    - { role: samba, tags: samba }
    - { role: libvirt, tags: libvirt }
    - { role: docker, tags: docker }
    - { role: amdgpu, tags: amdgpu}
    - { role: desktop, tags: desktop }
    - { role: gnome, tags: gnome }
  tasks:
    - name: Set sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop: "{{ sysctl_params | dict2items }}"

    - name: Blacklist kernel modules
      community.general.kernel_blacklist:
        name: "{{ ga402r_kernel_blacklist }}"
        state: present

    - name: Install laptop packages
      community.general.pacman:
        name: "{{ ga402r_packages }}"
        state: present

    - name: Enable and start laptop services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ ga402r_services }}"

    - name: Install all packages
      community.general.pacman:
        name: "{{ all_packages }}"
        state: present
