---
- ansible.builtin.import_playbook:
    archlinux.yml

- name: Configure GA402R laptop
  hosts: localhost
  become: true
  vars:
    packages: [power-profiles-daemon, asusctl, supergfxctl, switcheroo-control, rog-control-center]
    services: [power-profiles-daemon, asusd, supergfxd, switcheroo-control]
    kernel_blacklist: [sp5100_tco, wdat_wdt] # watchdog
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars:
        file: vars.yml
      tags: always
  roles:
    - { role: samba, tags: samba }
    - { role: libvirt, tags: libvirt }
    - { role: docker, tags: docker }
    - { role: amdgpu, tags: amdgpu}
    - { role: desktop, tags: desktop }
    - { role: plasma, tags: plasma }
  tasks:
    - name: Set sysctl parameters
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop: "{{ sysctl_params | dict2items }}"
      tags: sysctl

    - name: Blacklist kernel modules
      community.general.kernel_blacklist:
        name: "{{ kernel_blacklist }}"
        state: present
      tags: modprobe

    - name: Install laptop packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      tags: packages

    - name: Enable and start laptop services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop: "{{ services }}"
      tags: services

    - name: Install all packages
      ansible.builtin.package:
        name: "{{ all_packages }}"
        state: present
      tags: packages
