---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Change user shell
  ansible.builtin.user:
    name: "{{ user | default(ansible_user) }}"
    shell: /bin/zsh

- name: Clean up bash files
  ansible.builtin.file:
    path: "/home/{{ user | default(ansible_user) }}/{{ item }}"
    state: absent
  loop:
    - .bash_history
    - .bash_logout
    - .bash_profile
    - .bashrc
  when: zsh_cleanup_bash
