---
- name: Install packages
  community.general.pacman:
    name:
      - mesa
      - xf86-video-amdgpu
      - vulkan-radeon
      - libva-mesa-driver
      - mesa-vdpau
      - rocm-smi-lib
    state: present

- name: Install 32-bit packages
  community.general.pacman:
    name:
      - lib32-mesa
      - lib32-vulkan-radeon
      - lib32-libva-mesa-driver
      - lib32-mesa-vdpau
    state: present
  failed_when: false

- name: Create /etc/mkinitcpio.conf.d/amdgpu.conf
  ansible.builtin.copy:
    content: "MODULES+=(amdgpu)\n"
    dest: /etc/mkinitcpio.conf.d/amdgpu.conf
    mode: '0644'

- name: Regenerate initramfs
  ansible.builtin.command:
    cmd: mkinitcpio -P
